#!/bin/bash

if [ -z "$AUTH_URL" ]; then
  AUTH_URL=`grep AVALON.AUTH_URL /opt/adobe/ams/conf/ams.ini | cut -d '=' -f 2 | sed 's/^ *//g'`
fi

while read uri; do
  saveIFS=$IFS
  IFS='=&'
  parm=($uri)
  IFS=$saveIFS
  curl_cmd="curl -s ${AUTH_URL}.txt?token=${parm[1]}"
  raw=`${curl_cmd}`
  result='/avalon/forbidden'
  for seg in $raw; do 
    valid=`echo ${uri} | grep /${seg}`
    if [ -n "${valid}" ] && [ -n "${seg}" ]; then
      result=$uri
      break
    fi
  done
  echo $result
done
