#!/bin/bash

while read uri; do
  saveIFS=$IFS
  IFS=';'
  parm=($uri)
  IFS=$saveIFS
  AUTH_URL=`echo ${parm[0]} | perl -pe 's/(.+)(assets|media_objects|master_files).+$/$1/'`
  curl_cmd="curl -s ${AUTH_URL}authorize.txt?token=${parm[2]}"
  raw=`${curl_cmd}`
  result='/avalon/forbidden'
  for seg in $raw; do
    valid=`echo ${uri} | grep /${seg}`
    if [ -n "${valid}" ] && [ -n "${seg}" ]; then
      result=${parm[1]}
      break
    fi
  done
  echo $result
done
